version: "2"
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - revive
    - misspell
    - depguard
    - nestif    
    - dupl
  settings:
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: var-naming
        - name: unused-parameter
output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
