services:
  be-border-service:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: be-border-service
    ports:
      - "8080:3001"
    network_mode: host    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Akuntest1!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-dashboard
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - redis_insight:/data
volumes:
  sqlserverdata: